    ADDITIONAL_PACKAGES=(
        "colorlog==6.10.1"
        "home-assistant-frontend==20260128.6"
        "pymicro-vad==1.0.1"
        "pyspeex-noise==1.0.2"
        "mutagen==1.47.0"
        "ha-ffmpeg==3.2.2"
        "hassil==3.5.0"
        "home-assistant-intents==2026.1.28"
        "PyTurboJPEG==1.8.0"
        "av==16.0.1"
        "go2rtc-client==0.4.0"
        "PyNaCl==1.6.2"
        "openai==2.15.0"
        "RestrictedPython==8.1"
        "numpy==2.3.2"
        "bleak-retry-connector==4.4.3"
        "habluetooth==5.8.0"
        "aiousbwatcher==1.1.1"
        "pyserial==3.5"
        "python-matter-server==8.1.2"
        "aiodhcpwatcher==1.2.1"
        "aiodiscover==2.7.1"
        "file-read-backwards==2.0.0"
        "async-upnp-client==0.46.2"
        "bluetooth-adapters==2.1.0"
    )
    
    for pkg in "${ADDITIONAL_PACKAGES[@]}"; do
        log_info "正在安装 $pkg..."
        pip install "$pkg" || log_error "无法安装依赖包 '$pkg'。请检查网络连接或包名是否正确。"
    done
